Repository Every-Board/EB-BACKEND, pull requests merged in 2023-05, with the labels that each got.

#8 feat: 초기 세팅, User Entity 구현
  src/main/java/com/java/everyboard/audit/Auditable.java
  src/main/java/com/java/everyboard/constant/ActiveStatus.java
  src/main/java/com/java/everyboard/constant/LoginType.java
  src/main/java/com/java/everyboard/exception/BusinessLogicException.java
  src/main/java/com/java/everyboard/exception/ErrorResponse.java
  src/main/java/com/java/everyboard/exception/ExceptionCode.java
  src/main/java/com/java/everyboard/exception/GlobalExceptionAdvice.java
  src/main/java/com/java/everyboard/home/HomeController.java
  src/main/java/com/java/everyboard/user/User.java
Labels: feat

#20 feat:comment,comment heart 구현
  src/main/java/com/java/everyboard/comment/controller/CommentController.java
  src/main/java/com/java/everyboard/comment/dto/CommentPatchDto.java
  src/main/java/com/java/everyboard/comment/dto/CommentPostDto.java
  src/main/java/com/java/everyboard/comment/dto/CommentResponseDto.java
  src/main/java/com/java/everyboard/comment/entity/Comment.java
  src/main/java/com/java/everyboard/comment/mapper/CommentMapper.java
  src/main/java/com/java/everyboard/comment/repository/CommentRepository.java
  src/main/java/com/java/everyboard/comment/service/CommentService.java
  src/main/java/com/java/everyboard/commentheart/controller/CommentHeartController.java
  src/main/java/com/java/everyboard/commentheart/dto/CommentHeartPostDto.java
  src/main/java/com/java/everyboard/commentheart/dto/CommentHeartResponseDto.java
  src/main/java/com/java/everyboard/commentheart/entity/CommentHeart.java
  src/main/java/com/java/everyboard/commentheart/mapper/CommentHeartMapper.java
  src/main/java/com/java/everyboard/commentheart/repository/CommentHeartRepository.java
  src/main/java/com/java/everyboard/commentheart/service/CommentHeartService.java
Labels: feat

#22 Refactor: 1주차 dev merge 수정사항
  build.gradle
  src/main/java/com/java/everyboard/AwsS3/AwsS3Service.java
  src/main/java/com/java/everyboard/content/dto/CategoryResponseDto.java
  src/main/java/com/java/everyboard/content/dto/ContentAllResponseDto.java
  src/main/java/com/java/everyboard/content/dto/ContentResponseDto.java
  src/main/java/com/java/everyboard/content/dto/HomepageContentResponseDto.java
  src/main/java/com/java/everyboard/content/dto/UserContentResponseDto.java
Labels: refactor

#23 Feat: User, 보안/인증 기능 구현
  build.gradle
  src/main/java/com/java/everyboard/AwsS3/AwsS3Service.java
  src/main/java/com/java/everyboard/comment/service/CommentService.java
  src/main/java/com/java/everyboard/commentheart/controller/CommentHeartController.java
  src/main/java/com/java/everyboard/config/SecurityConfig.java
  src/main/java/com/java/everyboard/contentHeart/controller/ContentHeartController.java
  src/main/java/com/java/everyboard/exception/ExceptionCode.java
  src/main/java/com/java/everyboard/scrap/controller/ScrapController.java
  src/main/java/com/java/everyboard/security/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/java/everyboard/security/auth/filter/JwtVerificationFilter.java
  src/main/java/com/java/everyboard/security/auth/handler/MemberAccessDeniedHandler.java
  src/main/java/com/java/everyboard/security/auth/handler/MemberAuthenticationEntryPoint.java
  src/main/java/com/java/everyboard/security/auth/handler/MemberAuthenticationFailureHandler.java
  src/main/java/com/java/everyboard/security/auth/handler/MemberAuthenticationSuccessHandler.java
  src/main/java/com/java/everyboard/security/auth/jwt/JwtTokenizer.java
  src/main/java/com/java/everyboard/security/auth/userdetails/MemberDetailsService.java
  src/main/java/com/java/everyboard/security/dto/LoginDto.java
  src/main/java/com/java/everyboard/security/utils/CustomAuthorityUtils.java
  src/main/java/com/java/everyboard/security/utils/ErrorResponder.java
  src/main/java/com/java/everyboard/user/controller/UserController.java
  src/main/java/com/java/everyboard/user/entity/User.java
  src/main/java/com/java/everyboard/user/mapper/UserMapper.java
  src/main/java/com/java/everyboard/user/service/UserService.java
Labels: feat

#24 Refactor: Content domain
  src/main/java/com/java/everyboard/content/controller/ContentController.java
  src/main/java/com/java/everyboard/content/dto/CategoryResponseDto.java
  src/main/java/com/java/everyboard/content/dto/ContentAllResponseDto.java
  src/main/java/com/java/everyboard/content/dto/ContentPatchDto.java
  src/main/java/com/java/everyboard/content/dto/ContentPostDto.java
  src/main/java/com/java/everyboard/content/dto/ContentResponseDto.java
  src/main/java/com/java/everyboard/content/dto/HomepageContentResponseDto.java
  src/main/java/com/java/everyboard/content/dto/UserContentResponseDto.java
  src/main/java/com/java/everyboard/content/entity/Content.java
  src/main/java/com/java/everyboard/content/repository/ContentImageRepository.java
  src/main/java/com/java/everyboard/content/service/ContentService.java
Labels: refactor

#27 Refactor: CommentMapper, CommentHeartMapper 어노테이션 추가
  src/main/java/com/java/everyboard/comment/mapper/CommentMapper.java
  src/main/java/com/java/everyboard/commentheart/mapper/CommentHeartMapper.java
Labels: refactor

#26 Refactor: Content 도메인 오류 수정
  src/main/java/com/java/everyboard/content/dto/HomepageContentResponseDto.java
  src/main/java/com/java/everyboard/content/mapper/ContentMapper.java
  src/test/java/com/java/everyboard/content/controller/ContentControllerTest.java
Labels: refactor

#28 Feat: UserController 구현
  src/main/java/com/java/everyboard/user/controller/UserController.java
Labels: feat

#29 fix: CustomAuthorityUtils 오류 수정
  build.gradle
  src/main/java/com/java/everyboard/EveryboardApplication.java
  src/main/java/com/java/everyboard/security/utils/CustomAuthorityUtils.java
  src/main/java/com/java/everyboard/user/controller/UserController.java
  src/main/java/com/java/everyboard/user/dto/UserResponseDto.java
Labels: fix
